name: build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version-file: "go.mod"
      - run: go build .
      - run: go test -short ./... -v -race -coverprofile=coverage.txt -covermode=atomic
        env:
          BITBUCKET_TEST_TOKEN: ${{ secrets.BITBUCKET_TEST_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
